### POST /categories
POST http://localhost:3001/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.
eyJpZCI6MywiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTcwNjY2Njc0NywiZXhwIjoxNzA3MjcxNTQ3fQ.
8FHUdjqMpgrgB0uJvhqOiNaiAipe2G10DrP0nS00Opo

{
  "name": "Category 1"
}

### GET /categories
GET http://localhost:3001/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.
eyJpZCI6MywiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTcwNjY2Njc0NywiZXhwIjoxNzA3MjcxNTQ3fQ.
8FHUdjqMpgrgB0uJvhqOiNaiAipe2G10DrP0nS00Opo